language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS multilingual;"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - travis_retry composer update --dev --prefer-dist --no-interaction

script:
  - |
    vendor/bin/codecept run